id: PDE80D4E5
initial_creation_type: input
source_metadata:
  title: Orgyen Tendzin Norbu Series
  language: zh
  description: 'Texts by and about Orgyen Tendzin Norbu (o rgyan bstan ''dzin nor
    bu, 1841–1900), one of the main disciples of Dza Patrul Rinpoche:'
  volume:
    8ab44f3a2d6949dc9652df3b1452b27f:
      title: On the Final Words of Orgyen Tendzin Norbu
      parent: Commentaries
created_at: '2022-03-01T01:07:35.101635'
last_modified_at: '2022-03-01T01:07:35.101637'
